# fly.toml app configuration file generated for bumipro on 2023-08-26T05:11:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bumipro"
primary_region = "syd"

[build]
  image = "nestorsierra/bumipro:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dg3ovcugl"
  Cloudinary__ApiKey="972978461557492"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
